command:
  - uvicorn
  - app:app
  - --host
  - 0.0.0.0
  - --port
  - "8000"

resources:
  - name: databricks_host_secret
    secret:
      scope: databricks-app-secrets
      key: databricks_host
  - name: databricks_http_path_secret
    secret:
      scope: databricks-app-secrets
      key: databricks_http_path
  - name: databricks_token_secret
    secret:
      scope: databricks-app-secrets
      key: databricks_token

env:
  - name: DATABRICKS_HOST
    valueFrom: databricks_host_secret
  - name: DATABRICKS_HTTP_PATH
    valueFrom: databricks_http_path_secret
  - name: DATABRICKS_TOKEN
    valueFrom: databricks_token_secret
