command:
  - uvicorn
  - app:app
  - --host
  - 0.0.0.0
  - --port
  - "8000"

env:
  - name: DATABRICKS_HOST
    value: "{{secrets/databricks-app-secrets/databricks_host}}"
  - name: DATABRICKS_HTTP_PATH
    value: "{{secrets/databricks-app-secrets/databricks_http_path}}"
  - name: DATABRICKS_TOKEN
    value: "{{secrets/databricks-app-secrets/databricks_token}}"
